### ISSUE TITLE
Create communication module

### ISSUE THREAD

**Issue by rikkertkoppes** [FirstLegoLeague/fllscoring#11]
Also see #2 

The application should be able to communicate with the outside world.

**Comment by kmeesters** [comment]
Is still issue still relevant @rikkertkoppes (mhub)?

**Comment by poelstra** [comment]
This appears to be less related to mhub. It mostly describes how to fetch e.g. team lists, and submit scores.

This has already been implemented by now, although plans for improvement are also in progress.
What's still missing is 'live updates' to all clients (e.g. when team list or settings have changed). This last item could be done with the help of mhub, but I think we can better close this issue and open a separate issue(s) specifically for these items.
