### ISSUE TITLE
Offer as service

### ISSUE THREAD

**Issue by kmeesters** [FirstLegoLeague/fllscoring#124]
Considering offering the scoring applications as a hosted service for location with internet and 4G enabled devices. Implies an additional layer in the hierarchy (multiple tournaments, belonging to an organizer), more security and more maintenance. However chances are that it might create a huge impact. 

Feel free to share your thoughts.

**Comment by rikkertkoppes** [comment]
Steps to take

- allow configuration of data dir by command line
- extend andever to work with cli parameters and extendable config
- adjust app to work in a context
- setup nginx to route different contexts to different instances.

**Comment by rikkertkoppes** [comment]
This is done
