### ISSUE TITLE
Ignore practice round in overall score

### ISSUE THREAD

**Issue by robvw** [FirstLegoLeague/fllscoring#132]
The system currently has no notion of "practice rounds"; rounds which should be ignored when determining maximum scores and rankings.

**Comment by poelstra** [comment]
Unless I'm missing something, this scenario is already supported.

It's simply a matter of adding a 'practice' stage (like any other stage).
Rankings are only computed within a stage, so any scores gathered during the practice rounds does not influence scores of the 'real' rounds.

**Comment by robvw** [comment]
My bad, I thought there was an overall ranking based on all scores.
