### ISSUE TITLE
Warning when clicking disabled "Save" button

### ISSUE THREAD

**Issue by robvw** [FirstLegoLeague/fllscoring#133]
Currently the "Save" button is disabled when the form has not been completely filled in yet. To some referees this is not obvious; they click the button and automatically assume the score was saved (giving no feedback causes a "no news is good news" assumption that submission worked).

The application would be more robust if clicking "Save" while it is disabled causes explicit feedback (flash the preventSaveErrors in red, display those same messages in a popup, something like that).

**Comment by kmeesters** [comment]
Suggest to add a persitent message next to the button (or above) that signals form is not compelete. Message disappears when form is filled in correctly

**Comment by robvw** [comment]
This was actually already fixed in 1fb268b71a44f75c4a34f2cd31e96e2146c91b55.
