### ISSUE TITLE
Export scores to for use on a separate laptop / screen

### ISSUE THREAD

**Issue by kmeesters** [FirstLegoLeague/fllscoring#136]
Export scores in a file that can be used straightaway (standalone) to shows the scores during competitions. Should include high-scores up to a certain round, sorted by rakning. 

Includes: team nr, team name, high score, ranking
Optionally includes mark for teams that have not competed in all round up to the export round (for example exporting round 2 when not all teams have played their 2nd round)

File / export should be able to be opened on seperate that is not connected live to the scoring application

**Comment by Jheronymus** [comment]
added via PR merge 88b49a6165ab18631989b97a0e0ec7035d30d32b
