### ISSUE TITLE
Sort teamlist by teamname on the ref sheet

### ISSUE THREAD

**Issue by kmeesters** [FirstLegoLeague/fllscoring#137]
Can be set now by default to teamname.
Ideally make it configguable (large events prefer team numbers over names)

**Comment by robvw** [comment]
Implemented in 56378c421fad5d2fc781298fedb3a701ebf4ab99 and 1f4d4f2f331a00fb598df8f31be4fee79d58c113

The settings persistently keep a per-event default sort order. Each referee can toggle the sort order to their personal preference (only remembered until the next reload).
