### ISSUE TITLE
Make stage property of round object

### ISSUE THREAD

**Issue by kmeesters** [FirstLegoLeague/fllscoring#141]
Reverse relationship between stages and rounds.

**Comment by kmeesters** [comment]
Or import / export function to move socres to different rounds

**Comment by poelstra** [comment]
This is no longer considered necessary. If a round needs to be 'moved' (e.g. from practice round to official round), edit the stage/round properties of the scores themselves (i.e. not the underlying scoresheet, just the meta info). See #59 for the full discussion.
