### ISSUE TITLE
List of XML challenges available

### ISSUE THREAD

**Issue by Jheronymus** [FirstLegoLeague/fllscoring#144]
On the settings page you currently have to know the name of the XML file and type it in correctly.

A simple improvement would be a dropdown list with options available locally.

A good way to implement this is to have the grunt XML->js builder make a json with all challenges and put the result in the data folder.

**Comment by rikkertkoppes** [comment]
Makes sense. But no priority i guess. We will set 2015 as default as soon as it is ready.

**Comment by poelstra** [comment]
Can't we even set the year automatically based on current date? e.g.
everything before july XXXX is challenge_(XXXX-1).xml, everything after
that is challenge_XXXX.xml ?

**Comment by Jheronymus** [comment]
I will set the default to the latest English version, but I think it should be easier to change it to a translation.

**Comment by rikkertkoppes** [comment]
I was browsing through my memories. The idea was to get a list of available challenges at a central server, as well as being able to upload custom ones (e.g. for translations or another tournament altogether).

As I am about to split server behaviour in 1. File system emulation and 2. Central repository anyway, this would be a nice addition to add to the central repo.

The repo provides a list of challenges, which, upon select, get saved in the file system.

**Comment by kmeesters** [comment]
I'd maybe ask to change the 'scrap cars' mission to yes/no questions. Though i understand the elegance of button the options in the button text, it messes up the UI (not so clean anymore in some screen sizes)

**Comment by kmeesters** [comment]
Let's rescope this to creating a dropdown based on the XML or JS files present in the file structure. Will make a separate for version control/verification against central server.
