### ISSUE TITLE
add 2015 Trash Trek mission definition in Dutch

### ISSUE THREAD

**Issue by Jheronymus** [FirstLegoLeague/fllscoring#145]
Use the official translation. After the options have been defined, this can be a base for the other languages.

Please use this issue for feedback.

**Comment by Jheronymus** [comment]
I think we need a better way to model the 'Scrap cars'/'Sloop auto' mission
Perhaps three yes/no combo's that work together?

**Comment by rikkertkoppes** [comment]
We could, but this would induce one invalid combination (which can be checked and reported to the user)

The current situation prevents that, but may be less intuitive indeed.

Let's ask our referees for feedback

**Comment by rikkertkoppes** [comment]
@sleemans any input on this?

**Comment by sleemans** [comment]
Yes, I have.
We expect the first Q&A and official score sheet to be published soon by US FIRST; after that the score sheet can be constructed.

**Comment by kmeesters** [comment]
Btw, here is first other version, as extra input: http://ev3lessons.com/resources/scorer/

**Comment by sleemans** [comment]
I updated the Dutch missions to reflect the current interpretation. Might need rework on the next Q&A's

**Comment by Jheronymus** [comment]
Missie titel moet alleen worden gebruikt voor het nummer / titel. De verwijzing naar de V&A kan beter in de help bij de missie. De tekst "M01/04 (V&A 11) " maakt de titel erg onleesbaar.

**Comment by Jheronymus** [comment]
c0e194042f1ee6e4b17e871c63815aadd1cf2987
