### ISSUE TITLE
Create a demo server

### ISSUE THREAD

**Issue by rikkertkoppes** [FirstLegoLeague/fllscoring#147]
Set up a server for demo purposes.

- follow the installation guidelines in the readme
- create a service that fires up `node localserver.js -u username:password` (not sure we need to have basic auth, but we might)
- create a set of anonymized teams, create some schedule
- create a cron job that refreshes the data directory every hour or so
- maybe create a supporting entry page or banner at the top. This can be done with an extra page hoested separately. Do NOT edit the repo as this makes updating the demo site cumbersome

**Comment by Jheronymus** [comment]
Could we use the gh-pages for the supporting site? Perhaps make it a dual site, one with the absolute latest check-out and one with the latest tag

**Comment by rikkertkoppes** [comment]
Yes and no. You can only host statics on gh-pages, no server logic. So the node application still needs a server.

However, we may use gh-pages for the supporting entry page. That would make it manageable too.
It could load the actual application in an iframe, solving the banner thingy as well

**Comment by kmeesters** [comment]
Have to keep in mind that the data store is not local, so we either need to
provision seperate accounts or reset the enviroment.


With kind regards,

*Kenny Meesters*
|T| +31 6 2462 1391
|T| +1 (718) 395 3718
* |S| k.meesters *

* |E| k.meesters@gmail.com <k.meesters@gmail.com>*

* Twitter <http://twitter.com/k_meesters> | *
* Facebook <http://facebook.com/k.j.m.g.meesters> | *
* LinkedIn <http://nl.linkedin.com/in/kmeesters> | *Availability
<http://doodle.com/kmeesters>


2015-08-26 11:58 GMT+02:00 Jeroen <notifications@github.com>:

**Comment by rikkertkoppes** [comment]
hence the fourth point

**Comment by kmeesters** [comment]
Currently running on the google app engine (compute instance). Linked to this github repo http://104.197.103.180:1390/

**Comment by rikkertkoppes** [comment]
Wrapped gh-pages around it: http://firstlegoleague.github.io/fllscoring/
Also referenced on the top of the repo homepage

**Comment by Jheronymus** [comment]
We should add a few demo teams and rename the rounds to English names.

**Comment by kmeesters** [comment]
Cronjob set every 30 min: restore teams.sjon and settings.json (3 teams). Delete scores.json and scoresheet folder. (in fact copied to a different folder as backup just in case some does use it 'live' ;)).
