### ISSUE TITLE
Fix export mimetype

### ISSUE THREAD

**Issue by rikkertkoppes** [FirstLegoLeague/fllscoring#155]
Any reason specifically to export as csv:
https://github.com/FirstLegoLeague/fllscoring/blob/master/src/js/views/ranking.js#L150

If so, add a comment, otherwise fix

**Comment by Jheronymus** [comment]
Not sure, I asked Felix about this.

**Comment by Jheronymus** [comment]
Update: no particular reason, it was just copied from other place. I'll update it.

**Comment by Jheronymus** [comment]
This was fixed in commit d9b5e8555446a29db82f33e1192778664b33e4da
