### ISSUE TITLE
long title breaks close button

### ISSUE THREAD

**Issue by Jheronymus** [FirstLegoLeague/fllscoring#156]
Steps to replicate.
Open IE11
Open score form.
Open info on first mission. Button misplaced and is unclickable.
![button-fail](https://cloud.githubusercontent.com/assets/2046231/10896199/aec9bc5e-81b8-11e5-9c57-df2256b98dc5.png)

**Comment by Jheronymus** [comment]
after review... only the very top of the button works.

**Comment by rikkertkoppes** [comment]
Added ellipsis:

![image](https://cloud.githubusercontent.com/assets/302821/11319978/3ec949b0-908b-11e5-98cb-8d4b84b6d0e7.png)
