### ISSUE TITLE
EN and NL challenge discrepancies

### ISSUE THREAD

**Issue by rikkertkoppes** [FirstLegoLeague/fllscoring#159]
There are differences between nl and en challenges. I have no idea which is correct (if any)

This is a major hurdle in our confidence to be able to correctly supply a working system tomorrow

![image](https://cloud.githubusercontent.com/assets/302821/11293885/d0820708-8f5e-11e5-8900-2f9c0f103359.png)

![image](https://cloud.githubusercontent.com/assets/302821/11293900/f7684ec2-8f5e-11e5-8074-308b1ad23acf.png)

![image](https://cloud.githubusercontent.com/assets/302821/11293909/0e210de8-8f5f-11e5-880d-30019125505e.png)

**Comment by rikkertkoppes** [comment]
Eindhoven feedback:

- M01/M04 recycled: max should be 2 containers (as nl)
- M02 methane: NL is ok
- M04 black bars: max 8 is correct (nl)
- M06 scrap cars: nl is ok
- M08: nl version prevents conflict

**Comment by sleemans** [comment]
The Dutch version is correct. The English version is outdated and should not be used.

**Comment by rikkertkoppes** [comment]
This makes it less critical

However, I think all language versions should always be up to date. So leaving this open until EN is up to par.

Also see #161 as an effort to try to minimize these discrepancies in the future

**Comment by kmeesters** [comment]
@robvw Can you check this with @sleemans and update the EN XML?

**Comment by sleemans** [comment]
Working on the English version...
