### ISSUE TITLE
Remember table and referee on score submission 

### ISSUE THREAD

**Issue by sleemans** [FirstLegoLeague/fllscoring#164]

**Comment by rikkertkoppes** [comment]
I assume the given table and referee should be remembered per device? That sounds reasonable.

I guess this is something that should take priority, as it can save a lot of repetitive tasks

**Comment by sleemans** [comment]
Correct: It would be nice if the device remembered that. For me it would be a nice to have.
________________________________
Van: Rikkert Koppes<mailto:notifications@github.com>
Verzonden: ‎21-‎11-‎2015 18:49
Aan: FirstLegoLeague/fllscoring<mailto:fllscoring@noreply.github.com>
CC: Leemans, S.J.J.<mailto:s.j.j.leemans@tue.nl>
Onderwerp: Re: [fllscoring] Remember table and referee on score submission  (#164)


I assume the given table and referee should be remembered per device? That sounds reasonable.

I guess this is something that should take priority, as it can save a lot of repetitive tasks

**Comment by Jheronymus** [comment]
extends #58
