### ISSUE TITLE
Sum of black bars should be 12

### ISSUE THREAD

**Issue by sleemans** [FirstLegoLeague/fllscoring#166]
Give error if not

**Comment by rikkertkoppes** [comment]
Could you please elaborate? Is this a challenge def thing? Can it be solved with the current implementation?

**Comment by sleemans** [comment]
Yes, this is specific for this year and should be solved in the scoring xml. However, it would require 12*12*12 possibilities to define the error in the current xml formalism. I'll write a script to do that and open a new issue to solve it more elegantly for next years.
________________________________
Van: Rikkert Koppes<mailto:notifications@github.com>
Verzonden: ‎21-‎11-‎2015 18:43
Aan: FirstLegoLeague/fllscoring<mailto:fllscoring@noreply.github.com>
CC: Leemans, S.J.J.<mailto:s.j.j.leemans@tue.nl>
Onderwerp: Re: [fllscoring] Sum of black bars should be 12 (#166)


Could you please elaborate? Is this a challenge def thing? Can it be solved with the current implementation?

**Comment by rikkertkoppes** [comment]
Specifically 13*9*13 combinations, of which 81 yield points.

Fixed with merge
