### ISSUE TITLE
Better feedback on scoresheet errors

### ISSUE THREAD

**Issue by poelstra** [FirstLegoLeague/fllscoring#167]
When there's an error somewhere on the scoresheet, it prevents submission (with an error message), but it's not clear what mission contains the error.

In this case, a referee reported that sometimes the 'slider' on the scoresheet could be visually indicating "0", but the underlying model would think it was still 'undefined' (separate issue, but still).

**Comment by poelstra** [comment]
Suggestion is to e.g. mark the whole mission 'block' with e.g. (subtle) red background.

**Comment by Jheronymus** [comment]
I thought we had somekind of form validation in it at some point. Not sure why that was removed. But clearly marking or listing the invalid missions is a must to solve erros fast.

**Comment by poelstra** [comment]
We do have validation, but it's not visualized in the individual missions.

**Comment by rikkertkoppes** [comment]
Sounds like a huge timesaver and relatively easy. I'll try to get this done before next weekend.

I guess we'll need 3 states. Ok, blank and error (which we already have)

**Comment by rikkertkoppes** [comment]
Is this something?

- green tick if completed
- red cross if errored (also updated styling of the error bar a bit)

![image](https://cloud.githubusercontent.com/assets/302821/11335692/ae66b4a2-91de-11e5-8a51-ba5a59934576.png)

**Comment by poelstra** [comment]
Looking good! I like the very prominent visibility. One scroll across
the page immediately highlights the problem. 

Does the presence of such bars make the screen e.g. scroll out of view
unexpectedly? (as in: should this space be 'reserved' somehow?) 

On 2015-11-23 12:36, Rikkert Koppes wrote: 

> Is this something? 
> 
> * green tick if completed
> * red cross if errored (also updated styling of the error bar a bit)
> 
> [1] 
> 
> --
> Reply to this email directly or view it on GitHub [2].
 

Links:
------
[1]
https://cloud.githubusercontent.com/assets/302821/11335692/ae66b4a2-91de-11e5-8a51-ba5a59934576.png
[2]
https://github.com/FirstLegoLeague/fllscoring/issues/167#issuecomment-158910856

**Comment by rikkertkoppes** [comment]
That is a good observation. It does make the title shift, which may cause rewrapping of text on small screens.

I'll reserve the space

Also. I'll add a tick mark to the teams selection card as well. Then you'd have all green marks if everything is ok
