### ISSUE TITLE
Team list doesn't scroll through 

### ISSUE THREAD

**Issue by sleemans** [FirstLegoLeague/fllscoring#169]
In scoresheet

**Comment by poelstra** [comment]
@sleemans Can you be a bit more specific?

**Comment by sleemans** [comment]
In the scoresheet, when selecting a team, the team list can be scrolled. However, scrolling stops on the iPad as soon as the user stops touching. Desired behavior is that the scrolling continues.

**Comment by rikkertkoppes** [comment]
Are you referring to scrolling inertia / momentum?

**Comment by rikkertkoppes** [comment]
@sleemans I added inertial scrolling to dialogs. Can you check whether this was what you meant? If so, please close the issue

**Comment by sleemans** [comment]
Issue seems to be fixed :)
Dank u zeer vanuit België.
________________________________
Van: Rikkert Koppes<mailto:notifications@github.com>
Verzonden: ‎21-‎11-‎2015 19:56
Aan: FirstLegoLeague/fllscoring<mailto:fllscoring@noreply.github.com>
CC: Leemans, S.J.J.<mailto:s.j.j.leemans@tue.nl>
Onderwerp: Re: [fllscoring] Team list doesn't scroll through  (#169)


@sleemans<https://github.com/sleemans> I added inertial scrolling to dialogs. Can you check whether this was what you meant? If so, please close the issue
