### ISSUE TITLE
Editing number of rounds of a stage doesn't work

### ISSUE THREAD

**Issue by poelstra** [FirstLegoLeague/fllscoring#171]
In Settings, Stages&Rounds tab, click the up-arrow for the number of rounds of a stage, click Save Settings.
Number of rounds revert to what it was before.

**Comment by rikkertkoppes** [comment]
Cannot reproduce. Can you give exact steps?

**Comment by poelstra** [comment]
Hmmm, reproduces with above instructions for me, but here goes:

Put following in `data/stages.json`:
```
[{"id":"practice","name":"Oefenrondes","rounds":2,"index":0},{"id":"qualifying","name":"Voorrondes","rounds":3,"index":1},{"id":"eighth","name":"Achtste finales","rounds":0,"index":2},{"id":"quarter","name":"Kwartfinales","rounds":0,"index":3},{"id":"semi","name":"Halve finales","rounds":0,"index":4},{"id":"final","name":"Finale","rounds":1,"index":5}]
```
- Use /admin page
- Go to Settings
- Select Rounds & Stages tab
- Click up-arrow of "Achtste finales" to increase the 0 to 1
- Click Save Settings (at top or bottom of page)
- Note how "Achtste finales" has reverted to 0 again

**Comment by rikkertkoppes** [comment]
Seems to go wrong for every but the first stage. Even after resorting

**Comment by rikkertkoppes** [comment]
@poelstra created a patch fix here: https://github.com/rikkertkoppes/fllscoring/commit/c9764e895735d6981364431d40dbc8e49378dd37. What are your thoughts about it? 

The problem is that ng-stages _update discards allStages and rebuilds it. I am not quite sure where to solve this properly. As you are the architect of this, do you have any preference?

**Comment by rikkertkoppes** [comment]
Created a better fix here: https://github.com/rikkertkoppes/fllscoring/commit/7479a94746ff448410a5bbc2a67ef3d8ad7fe60b
