### ISSUE TITLE
Fix XML Scoring File for Training mission

### ISSUE THREAD

**Issue by scottdm** [FirstLegoLeague/fllscoring#198]
For the Training mission, the score for 7 pieces of manure in the Training and Research Area should be 35 (5 points each), not 40. The XML file now has:

<case> <index-ref value="7"  /> <points amount="40"  /> </case>
at line 286.

**Comment by sleemans** [comment]
Correct. Will be fixed shortly.

**Comment by sleemans** [comment]
fixed in #202
