### ISSUE TITLE
Fix XML description for Conservation mission

### ISSUE THREAD

**Issue by scottdm** [FirstLegoLeague/fllscoring#199]
For the Conservation mission, there are 20 points per pair of animals, with, according to the mission description "*The five optional animals listed in this mission are the only ones allowed for exchange.” It doesn’t matter which side each pair winds up on, both sides score the sum of all the pairs. Thus the maximum is 5 pairs or 100 points. The XML currently shows a maximum of 10 pairs or 200 points, and allowing for more points than are possible could be confusing, as there are other animals on the Field that shouldn’t count.

**Comment by sleemans** [comment]
Correct, will be fixed shortly.

**Comment by sleemans** [comment]
fixed in #202
