### ISSUE TITLE
M01 shark tank allows for invalid scores

### ISSUE THREAD

**Issue by jpschewe** [FirstLegoLeague/fllscoring#200]
You can select "None" for "Shark and take are completely in Target" and still select yes for "Shark touching only tank floor (NOT wall)" and "Nothing touched the Shark except the tank". This should report an error to the user.

**Comment by sleemans** [comment]
Why should this be an error and not just a 0-score?
I'd say the situation you described can physically occur, can't it?

**Comment by jpschewe** [comment]
You're correct, it's can't physically occur. However I've had lots of cases where refs mark things incorrectly because they missed something. So it's really nice to tell them that they have input an invalid score with a warning so that they know that there is a problem with their score sheet.
