### ISSUE TITLE
M15 should NOT be computed automatically

### ISSUE THREAD

**Issue by jpschewe** [FirstLegoLeague/fllscoring#201]
If you select all 7 manure discs as being in the training area, then the bonus applied as part of M15 should be applied automatically. There should be no reason to have the user enter this information.

**Comment by sleemans** [comment]
related to #198

**Comment by sleemans** [comment]
#213

**Comment by jpschewe** [comment]
However you can't compute it automatically anymore. I posted to slack last week that there was a challenge update. You can get the bonus without getting the individual points.

**Comment by sleemans** [comment]
Could you clarify how one could can get the bonus without the individual points for M09?
The only update I can relate to M09-M15 is the August 30 update, and that one only sets the number of Manure samples to 7.

**Comment by jpschewe** [comment]
To get the individual points you need to move the manure one at a time.
However  the scoring criteria for the bonus is that all manure are in the
box at the end of the match. Nothing about how they got there.

Sent from my mobile device

On Nov 14, 2016 6:39 AM, "sleemans" <notifications@github.com> wrote:

Could you clarify how one could can get the bonus without the individual
points for M09?
The only update I can relate to M09-M15 is the August 30 update, and that
one only sets the number of Manure samples to 7.


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/FirstLegoLeague/fllscoring/issues/201#issuecomment-260324915>,
or mute the thread

**Comment by jpschewe** [comment]
Robot Game Updates 3 November 2016
UPDATE 5 – THE SCOPE OF “MORE”
Official Ruling
Due to continuing uncertainty about D02 Bullet 3 (The scope of the “MORE,”
statement); we have decided to extend you the Benefit Of The Doubt as
follows:
• M04 – If multiple pieces of Food are in one area, but are not alike, only
the points for that particular Target Area do not count.
• M09 – If more than one Manure Sample is Transported at a time, only those
particular Manure Samples will not count.
Other/legally Transported Manure Samples are unaffected.

UPDATE 4 – FROG MODEL/FROG COUNT
Official Ruling
It is unclear when to treat the Frogs as two animals, so here are the
rulings:
• Each Frog meeting scoring requirements will score.
• It is OK to load the Frog Model at the start of the match.

**Comment by sleemans** [comment]
Ah, that’s a good one!

I’ll fix it.

**Comment by jpschewe** [comment]
Here's a link to the challenge description that we use.
https://github.com/jpschewe/fll-sw/blob/master/scoring/src/fll/resources/challenge-descriptors/fll-2016_animal-allies.xml

In the future I hope to be able to parse your description and combine it
with the extra information in mine.
