### ISSUE TITLE
M09-M15:  toggle issue

### ISSUE THREAD

**Issue by Dino5902** [FirstLegoLeague/fllscoring#208]
From FIRST LEGO League Engineering Tech, Mike G. 

M09-M15
o	Should just say M09
o	Toggle starts at 0 and forces you to toggle to 1 and then back to 0 if you wanted to enter a zero (Note: M03 has the same issue); whereas the rest of the toggles start off of the numbers and allow you to toggle right to begin at zero

**Comment by sleemans** [comment]
Toggle issues are a duplicate with #207 
M09-M15 related to #201
