### ISSUE TITLE
M15  

### ISSUE THREAD

**Issue by Dino5902** [FirstLegoLeague/fllscoring#211]
From FIRST LEGO League Engineering Tech, Mike G.

M15
o   Should not be able to hit “yes” if the answer to M09 was anything other than 7 (Note: the two missions are contingent on each other. Not sure the language you are using for this, but would need to add an if/else statement).

**Comment by sleemans** [comment]
This is not possible in the current xml structure.
Furthermore, this question is completely redundant, as its answer follows straightforwardly from another mission.
The solution I propose is to remove the question for M15 and automatically assign these points (see https://github.com/FirstLegoLeague/fllscoring/issues/201)
