### ISSUE TITLE
Penalties:  order of scoring options

### ISSUE THREAD

**Issue by Dino5902** [FirstLegoLeague/fllscoring#212]
From FIRST LEGO League Engineering Tech, Mike G.

Penalties
o   This one is also just cosmetic… but these scoring options seem to be arranged kind of odd as well. It goes 5, 4, 3, 2, 1, 0 instead of 0, 1, 2, 3, 4, 5 (Note: May make more sense to use the same toggle you did in the previous Missions. Also note that everything other than M01 section counts forward instead of backward. Someone not paying attention may click wrong answer).

**Comment by sleemans** [comment]
I'll reverse the order.
Experience has shown that the counting dials are not as accurate and easy to use as buttons, thus whenever possible, the refs prefer buttons over counting dials, so I propose to stick to buttons.
