### ISSUE TITLE
[Request] Dockerize

### ISSUE THREAD

**Issue by Naramsim** [FirstLegoLeague/fllscoring#214]
It could be useful to [dockerize](https://www.docker.com/) this repo in a container.
So we could deploy it easily

**Comment by rikkertkoppes** [comment]
We have thought of that, but it is not on our short term list, as we expect a very low fraction of our target group to be familiar and comfortable with docker.

That said, we are currently actively working on creating self contained binaries that can run on mac, win and linux. We expect to release those for a few repos within a few weeks

**Comment by Naramsim** [comment]
Ok, thanks for the quick reply.

You can close if you want

**Comment by kmeesters** [comment]
First releases are published, feel free to test them and keep your feedback and contributions coming. Thanks @Naramsim! 
https://github.com/FirstLegoLeague/fllscoring/releases
