### ISSUE TITLE
font-awesome not completely removed

### ISSUE THREAD

**Issue by Jheronymus** [FirstLegoLeague/fllscoring#220]
I noticed that the layout using http://localhost:1390/nocache.html was not correct.

This commit removed font-awesome, but there a few files unchanged:
3295967ccfe815ab67b0fcea2beab5f60cf0653d

.gitignore
src\fgindex.html
src\fllscoring.appcache
src\nocache.html
src\nwindex.html

**Comment by rikkertkoppes** [comment]
Fixed by cherry picking
