### ISSUE TITLE
Nochache.html opens admin interface

### ISSUE THREAD

**Issue by kmeesters** [FirstLegoLeague/fllscoring#226]
The nocache defaults to admin interface. It might be better to default this to the referee page (or implement differently, for example in a setting). 
Related to issue #225

**Comment by rikkertkoppes** [comment]
nocache should not be used in production.

Is there something wrong with the normal version that makes you use nocache?

**Comment by kmeesters** [comment]
Yes, issue #225 
I'm thinking rather then page, a manual refresh cache button in the settings (not sure if that suggestion makes sense?)

**Comment by rikkertkoppes** [comment]
Don't see how that is cache related, any evidence to back that up? Using nocache or a refresh cache button is circumventing the problem. In any case, data should never be cached. And as far as I can see, it is not in the cache manifest, so that should be ok.

**Comment by poelstra** [comment]
To clarify Rikkert's point: *data* (teams, scores, ...) should never cached, but the app itself (JS, HTML, CSS, ...) should.

I agree that nocache should never be communicated to people, except for development.
If nocache is needed in 'normal' scenarios, we should fix that.

**Comment by kmeesters** [comment]
Okay, I think people used the nocache.html in panick.
