### ISSUE TITLE
demo gives a 404

### ISSUE THREAD

**Issue by sleemans** [FirstLegoLeague/fllscoring#230]
http://firstlegoleague.github.io/fllscoring/

**Comment by Jheronymus** [comment]
gh-pages branch is gone :-(

**Comment by kmeesters** [comment]
Prob my fault, but good oppurtinity to recreate a more stable demo at fll-tools.com, in the meanwhile feel free to use the binaries for demo's :)

**Comment by kmeesters** [comment]
Fixed, (more robustly) http://demo.fll-tools.com:1390
