### ISSUE TITLE
Rename localserver.js -> scoringserver.js

### ISSUE THREAD

**Issue by kmeesters** [FirstLegoLeague/fllscoring#232]
For easier manageability in the cloud ;)

**Comment by rikkertkoppes** [comment]
Why does that lead to easier management?

I'd rather actually rename them all to index.js

**Comment by alanggreen** [comment]
One reason not to have them all index.js is because if you run the services with something like PM2 then it's harder to tell which is which

**Comment by Jheronymus** [comment]
can't we have both? like an alias?

**Comment by kmeesters** [comment]
You can use --name in PM2,
or even create a specific YML to configure PM2

http://pm2.keymetrics.io/docs/usage/quick-start/



With kind regards,

*Kenny Meesters*
|T| +31 6 2462 1391
|T| +1 (718) 395 9466
* |S| k.meesters *

* |E| k.meesters@gmail.com <k.meesters@gmail.com>*

* Twitter <http://twitter.com/k_meesters> | *
* Facebook <http://facebook.com/k.j.m.g.meesters> | *
* LinkedIn <http://nl.linkedin.com/in/kmeesters> | *Availability
<http://doodle.com/kmeesters>
