### ISSUE TITLE
Scorekeeper or Head ref must be able to view ranking of team scores

### ISSUE THREAD

**Issue by alanggreen** [FirstLegoLeague/fllscoring#241]
Head ref often needs the ability to see the status of teams - where they are in the ranking. This is important when making decisions during discussions on teams regarding their  missions where there is no agreement on whether a mission is successful or not.
Need to be able to sort by team name, team number and score.

**Comment by poelstra** [comment]
Isn't this what you want?

![image](https://user-images.githubusercontent.com/1025628/27795840-e80a1f5c-6007-11e7-8593-eea72f485886.png)

All columns can be clicked (and will sort/reverse sort).

Seems the sorting indicators stopped working though, I'll file a bug for that.

**Comment by poelstra** [comment]
@alanggreen can you please indicate whether the existing functionality (apart from bug #249) is what you meant? If so, please close this issue.
