### ISSUE TITLE
Error with M15 for hydrodynamic score sheet

### ISSUE THREAD

**Issue by jpschewe** [FirstLegoLeague/fllscoring#274]
There's an error in your scoresheet, you're allowing people to get the double manhole bonus without both manholes flipped over (M15).

http://www.fll-tools.com/general/hydrodynamics-scoresheet-online/

**Comment by sleemans** [comment]
M15 says: "The fire is dropped only by making the firetruck apply direct force to the house’s yellow lever.". This doesn't seem to have anything to do with manholes?

Mission M08 mentions manholes, but it seems to be working correctly: you can select 'yes' for the bonus, but no points will be credited.

Could you maybe clarify what the error is?

**Comment by jpschewe** [comment]
Yes I meant m08, sorry.

The fact that you can select it and no error is reported is the problem.
