### ISSUE TITLE
Launcher setup fails if the scoring software is running

### ISSUE THREAD

**Issue by alanggreen** [FirstLegoLeague/fllscoring#299]
When running the fll-scoring-setup program while a previous install is running, the installer tries, and fails, to shut the previous version down. 
You see this screen
![image](https://user-images.githubusercontent.com/6757517/32950674-df03b936-cbaf-11e7-9b13-e583ee681ea5.png)
and then after pressing Next you get
![image](https://user-images.githubusercontent.com/6757517/32950699-f939865a-cbaf-11e7-8a93-eee72b786903.png)

**Comment by kmeesters** [comment]
Not a scoring module issue
