### ISSUE TITLE
Website for dissmenation

### ISSUE THREAD

**Issue by kmeesters** [FirstLegoLeague/fllscoring#30]
* Create website and domain for sharing files and instructions
* Align with existing organizations (STP)
* Purchase domain and setup website

**Comment by rikkertkoppes** [comment]
@kmeesters just a thought: could we maybe setup this website as a git repo, hosted via gh-pages?

That would only allow static pages, but that would be fine for mostly static content. It has the additional benefit that maintaining it could be a joint development effort.

One thing I would like to start documenting on a higher level is (graphical maybe):

- what pieces of software are currently available (clock, mhub, display systems, twitter, scoring)
- how do those pieces work together, in various "growth levels"
- some introductory / explanatory video maybe?

**Comment by kmeesters** [comment]
This issue was moved to FirstLegoLeague/General-IT#4
