### ISSUE TITLE
Launcher splash page does not do word wrap correctly

### ISSUE THREAD

**Issue by alanggreen** [FirstLegoLeague/fllscoring#300]
1. The word FIRST is not wrapped at a word boundary
![image](https://user-images.githubusercontent.com/6757517/32950852-8f6dcd48-cbb0-11e7-92af-72d5b1a112b3.png)
2. FIRST should be in italics

**Comment by kmeesters** [comment]
This is not an fllscoring issue, but a launcher issue. Or at least not this code base
