### ISSUE TITLE
Table and referee entry

### ISSUE THREAD

**Issue by kmeesters** [FirstLegoLeague/fllscoring#58]
- An option (field) to select the referee name
- An option (fiedl) to select the table number or letter

**Comment by kmeesters** [comment]
This would be desirable for the Benelux finale, considering we have 12 tables in play. Quick hunting for referees providing incorrect input would help in quickly resolving issues. 

Note: in the Benelux table = referee (in general), but it doesn't have to be. I.e. a referee can switch or change tables. I imagine a similair construct as teams? A central store in the networked mode (for now).

**Comment by rikkertkoppes** [comment]
I added a table entry for now, as said, it would eventually migrate to a setting, but I decided not to go for a standalone version this time, since we have windows tablets

**Comment by rikkertkoppes** [comment]
Multiple tables and referees now possible with 883efa4efc363695a52715ba510a03f6d7e6386d

Still needs a select in scoresheet definition

**Comment by rikkertkoppes** [comment]
Done with 4f636ba55b7eb844827ccb9ecf96974a6b6eb470

@kmeesters can you check and close id adequate?
