### ISSUE TITLE
Create round and stages

### ISSUE THREAD

**Issue by kmeesters** [FirstLegoLeague/fllscoring#59]
An interfaace has been created in the settings see commit https://github.com/FirstLegoLeague/fllscoring/commit/07a5cf50bf3fe995f09c580f14b1e32ecf296f93

Martin has written the backend code (#42) someone needs to hook-up the frontend to the backend :)

**Comment by rikkertkoppes** [comment]
For pragmatic purposes (time), sticking to the current implementation:

- a round is just a number. Cannot be named, cannot be moved (across stages)
- stages can be named, ordered and number of rounds adjusted
- scores keep separated, they have nothing to do with stage definition

**Comment by rikkertkoppes** [comment]
Implemented like this:

![image](https://cloud.githubusercontent.com/assets/302821/10716113/57786530-7b2e-11e5-92d6-1ecb8a619793.png)

You can add stages, move them, edit them and delete them. Also added a wee bit material design, which will flow through the rest of the app.
