### ISSUE TITLE
Delete rounds and stages

### ISSUE THREAD

**Issue by kmeesters** [FirstLegoLeague/fllscoring#62]
Round and stages should be deleted only if:
- Stages contain no rounds
- Round contain no scores OR after repeated confirmation

Ideally rounds are not completely deleted but archived, (via status?)
See #63

**Comment by rikkertkoppes** [comment]
Stages can already be deleted, number of rounds can be changed as well.

There is no confimation, but I don't think it is needed anyway.

Any score or ranking copies stage and round data. No scores are ever lost by deleting stages or rounds.

**Comment by poelstra** [comment]
And in addition, the Scores view will show validation errors for any scores that now no longer belong to an existing stage/round. It is then possible to either delete or edit these scores.

**Comment by kmeesters** [comment]
perfect, just need to include this in documentation.
